config/routes.rb
Rails.application.routes.draw do
  get 'session/create'
  get 'session/destroy'
  get 'home/index'
  get 'auth/:provider/callback', to: 'session#create', via: [:get, :post]
  get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: 'session#destroy', as: 'signout', via: [:get, :post]
  resources :bookmarks
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
require 'uri'
class Bookmark < ApplicationRecord
    after_create :screenshot, :set_title
    validates :url, :format => URI::regexp(%w(http https)), presence: true

    belongs_to :user

    private
    def self.search(search)
        where('title LIKE ?', "%#{search}%")
    end
    def url_title
        URI.parse(url).host.sub(/\Awww\./, '')
    end

    def set_title
      update(title: URI.parse(url).host)
    end
    def screenshot
      ws = Webshot::Screenshot.instance
      screenshot = ws.capture url, "#{url_title}.png", width: 200, height: 128, quality: 85
      uploader = Cloudinary::Uploader.upload(screenshot.path)
      update(screenshot_url: uploader['url'])
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks
  def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:update, :edit, :destroy]
  def index
    @bookmark = Bookmark.new
    if params[:search]
      @bookmarks = Bookmark.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 4)
    else
      @bookmarks = Bookmark.all.paginate(page: params[:page], per_page: 4)
    end
  end
  def new
    #@bookmark = Bookmark.new
  end
  def create
    @bookmark = current_user.bookmarks.create(bookmark_params)
    redirect_to bookmarks_path
  end
  def update
    if @bookmark.update(bookmark_params)
      redirect_to bookmarks_path
    end
  end

  def edit
  end
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_path}
    end
  end
  private
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
  def bookmark_params
    params.require(:bookmark).permit(:url, :id_user, :screenshot_url, :title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all.collect(&:name)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark, remote: true do |f| %>
  <% if @bookmark.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@bookmark.errors.count, "error") %></h2>
    <ul>
    <% @bookmark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url, :for => 'url' %><br />
    <%= f.text_field :url , :placeholder => 'Should start with http or https', :class => 'form-control', :id => 'url' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn' %>
  </div>
<% end %>

app/views/bookmarks/_row.html.erb
<div class="bookmark">
  <h5><%= bookmark.title %></h5>
  <a href="<%= bookmark.url %>"><img src='<%= bookmark.screenshot_url %>' class="img"/></a>
  <div class="hidden">
    <% if current_user.id == bookmark.user_id %>
    <span><%= link_to '🖋', edit_bookmark_path(bookmark) %> <%= link_to '✕', bookmark_path(bookmark), method: :delete, remote: true, class: 'delete_bookmark' %></span>
    <% end %>
  </div>
</div>

app/views/bookmarks/create.js.erb
$('#bookmark_holder').prepend("<% j(render 'row', bookmark: @bookmark) %>");
$('form')[0].reset();
$('.collapse').collapse('toggle')

app/views/bookmarks/edit.html.erb
<h1> Edit bookmark <h1>
<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<div class="d-flex justify-content-center">
<%= form_tag(bookmarks_path, :method => "get", id: "search-form", class: "form-inline search d-flex flex-nowrap") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control" %>
  <%= submit_tag "🔍", :class => "btn btn-success" %>
<% end %>
</div>

<h1>Your bookmarks</h1>

<button class="btn btn-primary" id="add_bookmark" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Create bookmark
</button><br/>
<div class="collapse" id="collapseExample">
  <div class="">
    <%= render 'form' %>
  </div>
</div>
<br/>
<div id="bookmark_holder" class="d-flex justify-content-center">
  <% @bookmarks.each do |bookmark| %>
      <%= render 'row', bookmark: bookmark %>
  <% end %>
</div>
<div class="d-flex justify-content-center"><%= will_paginate(@bookmarks,  :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %></div>

app/views/bookmarks/new.html.erb
<%= form_for @bookmark, remote: true do |f| %>
  <% if @bookmark.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@bookmark.errors.count, "error") %></h2>
    <ul>
    <% @bookmark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', bookmarks_path %>

app/views/home/index.html.erb
<br />
<% @users.each do |u| %>
  <p><%= u %></p>
<% end %>
<div class="jumbotron">
  <h1 class="display-4">Welcome to bookmark app</h1>
  <p class="lead">Here you can make your gallery of bookmarks</p>
  <%= image_tag("screen.png", class: "img-fluid") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppBookmarks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <script type="text/javascript">
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '1027365290748195', // App ID
          status     : true, // check login status
          cookie     : true, // enable cookies to allow the server to access the session
          xfbml      : true  // parse XFBML
        });
      };
      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
      function checkLoginState() {
        FB.getLoginStatus(function(response) {
          statusChangeCallback(response);
        });
      }
   </script>
        <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Bidofan app</a>
                        <% if current_user %>
                            <%= link_to "Bookmarks", bookmarks_path, :class => 'navbar-link'  %>
                        <% end %>
                </div>
                    <p class="navbar-text pull-right">
                    <% if current_user %>
                        Logged in as
                        <strong><%= current_user.name %></strong>.
                        <%= link_to "Logout", signout_path, :class => 'navbar-link'  %>
                    <% else %>
                        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", :class => 'navbar-link' %>
                    <% end %>
                    </p>
            </div>
        </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>